export const products = [
  {
    id: "mantine-ui",
    name: "Mantine UI",
    description: "Mantine UI: 123 responsive components built with Mantine",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: true,
    isNew: true,
    isFeatured: true,
    categories: ["design", "templates", "tools"],
  },
  {
    id: "wsrv-nl",
    name: "wsrv.nl",
    description: "wsrv.nl is an image cache & resize service",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: true,
    isNew: false,
    isFeatured: false,
    categories: ["tools", "saas"],
  },
  {
    id: "play-nextjs",
    name: "play-nextjs",
    description: "Open-source SaaS Starter Kit and Boilerplate for Next.js",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: true,
    isNew: true,
    isFeatured: true,
    categories: ["framework", "templates"],
  },
  {
    id: "outstatic",
    name: "Outstatic",
    description: "Outstatic is a static site CMS that lives inside your Next.js install",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: true,
    isNew: false,
    isFeatured: true,
    categories: ["cms", "tools"],
  },
  {
    id: "monetag",
    name: "Monetag",
    description:
      "Monetag is a platform for monetization of desktop, mobile web and in-app audiences, remnant ad inventory, and more",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: false,
    isNew: false,
    isFeatured: false,
    categories: ["monetization", "saas"],
  },
  {
    id: "hikari",
    name: "Hikari",
    description: "A complete & open-source Next.js 14, Stripe and Supabase SaaS Starter Template using App Router",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: true,
    isNew: true,
    isFeatured: false,
    categories: ["templates", "framework"],
  },
  {
    id: "fumadocs",
    name: "Fumadocs",
    description: "The powerful framework for building documentation sites in Next.js",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: true,
    isNew: false,
    isFeatured: false,
    categories: ["framework", "tools"],
  },
  {
    id: "n8n-chinese",
    name: "n8n 中文教程",
    description: "n8n Chinese Tutorials",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: false,
    isNew: false,
    isFeatured: false,
    categories: ["learning"],
  },
  {
    id: "query-domains",
    name: "Query Domains",
    description:
      "Query Domains is a free bulk WHOIS checker tool for checking domain availability based on WHOIS lookups",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: false,
    isNew: false,
    isFeatured: false,
    categories: ["domain", "tools"],
  },
  {
    id: "preline-ui",
    name: "Preline UI",
    description:
      "Preline UI is an open-source set of prebuilt UI components based on the utility-first Tailwind CSS framework",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: true,
    isNew: true,
    isFeatured: true,
    categories: ["design", "templates"],
  },
  {
    id: "aiven",
    name: "Aiven",
    description:
      "Aiven is a unified, cloud-agnostic platform to stream, store, and serve open source data on any cloud",
    image: "/placeholder.svg?height=225&width=400",
    isFree: false,
    isOpenSource: false,
    isNew: false,
    isFeatured: true,
    categories: ["database", "hosting"],
  },
  {
    id: "socialscreenshots",
    name: "SocialScreenshots",
    description: "A free tool to create stunning visuals for your social networks!",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: false,
    isNew: true,
    isFeatured: false,
    categories: ["tools", "design"],
  },
  {
    id: "microlink",
    name: "Microlink",
    description:
      "Microlink is a fast, reliable, and scalable high-level API to control a headless browser built for businesses and developers",
    image: "/placeholder.svg?height=225&width=400",
    isFree: false,
    isOpenSource: false,
    isNew: false,
    isFeatured: false,
    categories: ["tools", "saas"],
  },
  {
    id: "saaskit",
    name: "SaaSKit",
    description:
      "A black authentication starter template (password reset, email verification and auth). Includes Auth.js, Prisma, and more",
    image: "/placeholder.svg?height=225&width=400",
    isFree: true,
    isOpenSource: true,
    isNew: true,
    isFeatured: true,
    categories: ["templates", "saas"],
  },
  {
    id: "featurebase",
    name: "Featurebase",
    description:
      "Streamline feedback collection, identify impactful product opportunities and scale faster by building the right features",
    image: "/placeholder.svg?height=225&width=400",
    isFree: false,
    isOpenSource: false,
    isNew: false,
    isFeatured: false,
    categories: ["tools", "saas"],
  },
]
